// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1pA4_AA6YprK-ourSmYrrAIBkAvvPaaE',
    appId: '1:1096357972875:web:0aa3b302ced8f7cbdd3d8e',
    messagingSenderId: '1096357972875',
    projectId: 'khoa-1fef3',
    authDomain: 'khoa-1fef3.firebaseapp.com',
    storageBucket: 'khoa-1fef3.firebasestorage.app',
    measurementId: 'G-ZCRVP6NTYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXkjYlTPvSHCeEWNt7pBzQ72DkPqrMOk',
    appId: '1:1096357972875:android:c1ca6cd746d4867ddd3d8e',
    messagingSenderId: '1096357972875',
    projectId: 'khoa-1fef3',
    storageBucket: 'khoa-1fef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Z6FLQaxQ4gC8XrtBaoFUYODH3Tk1LMs',
    appId: '1:1096357972875:ios:0045dce5b80f8d70dd3d8e',
    messagingSenderId: '1096357972875',
    projectId: 'khoa-1fef3',
    storageBucket: 'khoa-1fef3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Z6FLQaxQ4gC8XrtBaoFUYODH3Tk1LMs',
    appId: '1:1096357972875:ios:0045dce5b80f8d70dd3d8e',
    messagingSenderId: '1096357972875',
    projectId: 'khoa-1fef3',
    storageBucket: 'khoa-1fef3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1pA4_AA6YprK-ourSmYrrAIBkAvvPaaE',
    appId: '1:1096357972875:web:95dd9f9f779fa4d0dd3d8e',
    messagingSenderId: '1096357972875',
    projectId: 'khoa-1fef3',
    authDomain: 'khoa-1fef3.firebaseapp.com',
    storageBucket: 'khoa-1fef3.firebasestorage.app',
    measurementId: 'G-V5VV8P6MGW',
  );
}
